version: '3.3'

services:

  redis:
    image: redis:alpine
    volumes:
      - /opt/redis/data:/data:rw
      - /opt/redis/etc/redis.conf:/usr/local/etc/redis/redis.conf:rw
    ports:
      - "127.0.0.1:16379:6379"
    entrypoint: sh
    command: -c 'chmod 755 / && redis-server /usr/local/etc/redis/redis.conf'
    restart: always
